version: "3.9"

services:
  db:
    image: mysql:8
    container_name: kudwa_db
    environment:
      MYSQL_DATABASE: financial_data
      MYSQL_USER: root
      MYSQL_PASSWORD: your_mysql_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  migration:
    build: .
    container_name: kudwa_migration
    env_file: .env
    depends_on:
      - db
    command: python utils/config/db/migration.py

  scheduler:
    build: .
    container_name: kudwa_scheduler
    env_file: .env
    depends_on:
      - db
      - migration
    command: python scheduler/financial_pipeline.py

  api:
    build: .
    container_name: kudwa_api
    env_file: .env
    depends_on:
      - db
      - migration
    command: python api/server.py
    ports:
      - "8000:8000"

volumes:
  db_data:
